### ISSUE TITLE
Timeout::ExitException can be raised by nested timeouts 

### ISSUE THREAD

**Issue by trogd0r** [ruby/timeout#52]
### Behavior

Nested timeout blocks can result in a Timeout::ExitException being raised, rather than a Timeout::Error

### How to reproduce

The below will sometimes raise a Timeout::ExitException, sometimes a Timeout::Error (roughly 50/50).
  
```ruby
begin
  Timeout.timeout(2) do
    Timeout.timeout(2) do
      sleep 3
    end
  end
rescue Exception => e
  puts "raised a #{e.class}"
end
```

### Cause (maybe)

Hacking up the Timeout module as follows:

```ruby
module Timeout
  class Error
    def self.handle_timeout(message) # :nodoc:
      exc = ExitException.new(message)

      begin
        puts "yield #{exc.object_id} (#{message})"
        yield exc
      rescue ExitException => e
        puts "test #{e.object_id} vs #{exc.object_id} => #{exc.equal?(e)} (#{message})"
        raise new(message) if exc.equal?(e)
        puts "re-raise #{e.object_id}('#{e}') (#{message})"
        raise
      end
    end
  end
end

Timeout.timeout(2, nil, "outer timeout") do
  Timeout.timeout(2, nil, "inner timeout") do
    sleep 3
  end
end
```

shows that, when an ExitException is raised, the "inner" exception is being caught by the "outer" handle_timeout block. Suspicious this is the result of [indeterminate Thread#raise behavior](https://jvns.ca/blog/2015/11/27/why-rubys-timeout-is-dangerous-and-thread-dot-raise-is-terrifying/)?

### Environment

Ruby 3.3.5
Timeout 0.4.1
Ubuntu 24.04.1 running on WSL2

**Comment by eregon** [comment]
It sounds somewhat related to https://bugs.ruby-lang.org/issues/20314
I'll try to think about a fix when I have some time.

**Comment by hsbt** [comment]
FYI: https://github.com/ruby/ruby/pull/10851

**Comment by sergio-bobillier** [comment]
👋 We are experiencing this issue in our setup. But our experiments show that this only happens if both `timeout` calls have the same timeout value, for example the following test:

```ruby
RSpec.describe 'Timeout' do
  it 'times out' do
    expect do
      Timeout.timeout(2) do
        Timeout.timeout(2) do
          sleep 19
        end
      end
    end.to raise_error(Timeout::Error)
  end
end
```

Fails all the time with a `Timeout::ExitException` that RSpec is not able to `rescue`:

```
Failures:

  1) Timeout times out
     Failure/Error: output.__send__(method, *args, &block)

     Timeout::ExitException:
       execution expired
     # Backtrace omitted ...
     #
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 2.01 seconds (files took 0.13324 seconds to load)
2 examples, 1 failure
```

However, doing this change:

```diff
       Timeout.timeout(2) do
-        Timeout.timeout(2) do
+        Timeout.timeout(2.1) do
           sleep 19
```

Makes the test pass 100% of the time:

```
.

Finished in 2.01 seconds (files took 0.1275 seconds to load)
1 example, 0 failures
```

**Comment by eregon** [comment]
Taking a look at this and with:
```ruby
require 'timeout'

begin
  Timeout.timeout(2) do
    Timeout.timeout(2) do
      sleep 3
    end
  end
rescue Exception => e
  p e
end
```
I get this consistently:
```
$ ruby -v -Ilib repro_nesting1.rb
ruby 3.4.7 (2025-10-08 revision 7a5688e2a2) +PRISM [x86_64-linux]
#<Timeout::Error: execution expired>
repro_nesting1.rb:10:in 'Kernel#p': execution expired (Timeout::ExitException)
	from repro_nesting1.rb:10:in '<main>'
```
FWIW on 3.3 it's slightly different:
```
$ ruby -v -Ilib repro_nesting1.rb
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
#<Timeout::Error: execution expired>
repro_nesting1.rb:10:in `p': execution expired (Timeout::ExitException)
	from repro_nesting1.rb:10:in `rescue in <main>'
	from repro_nesting1.rb:3:in `<main>'
```

So the bad thing is the exception happens on line 10 which is `p e` and is *after* the Timeout.timeout blocks.
This is due to having multiple Thread#raise, as explained in https://bugs.ruby-lang.org/issues/20314

**Comment by eregon** [comment]
I think one idea would be to avoid calling Thread#raise in between another Thread#raise by Timeout and the `Request#finished` call, maybe using a lock per Fiber or so.
I need to try it.
