### ISSUE TITLE
incompatible with ractors

### ISSUE THREAD

**Issue by HoneyryderChuck** [ruby/timeout#53]
currently, `timeout` can't be used in ractors:

```ruby
Ractor.new do
  Timeout.timeout(4) do
    sleep(5)
  end
end.take
# .rubies/ruby-3.3.0/lib/ruby/3.3.0/timeout.rb:129:in `ensure_timeout_thread_created': can not access non-shareable objects in # # constant Timeout::TIMEOUT_THREAD_MUTEX by non-main ractor. (Ractor::IsolationError)
#         from .rubies/ruby-3.3.0/lib/ruby/3.3.0/timeout.rb:178:in `timeout'
#         from (irb):8:in `block in <top (required)>'
```

Lots of downstream dependencies rely on `timeout`, and this makes them unusable under ractors.

**Comment by eregon** [comment]
I think Thread in general is considered incompatible with Ractor (it breaks the programming model and there are several bugs with Ractor & threads), and so Timeout (which needs threads) is incompatible with Ractor.

**Comment by HoneyryderChuck** [comment]
I wouldn't go so far. If `timeout` would use ractor-local thread/queue/cond/mutex, it'd work. A completely alternative ractor-friendly implementation could also be an option. Was just pointing out that, the way it's implemented, it's unusable.

**Comment by jsvd** [comment]
Another point here is that the current implementation suffers in any ruby implementation that supports threading, like JRuby and TruffleRuby when using timeout for high throughput scenarios.

If multiple threads are doing very short lived timeout blocks, then the cleanup thread can easily be too slow and start accumulating Timeout.Request objects until and OOM happens.

A lot more details into this issue can be found in https://github.com/jruby/jruby/issues/8406#issuecomment-2455244021.

As it stands it's not an issue in MRI given it doesn't work in ractors, so the clean up thread is never overwhelmed.

**Comment by jsvd** [comment]
@eregon fair enough, I moved the comment to a new issue https://github.com/ruby/timeout/issues/58
